# Generated by Django 5.0.3 on 2024-03-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Account',
            fields=[
                ('SOL_ID', models.CharField(max_length=50)),
                ('ACCT_MGR_USER_ID', models.CharField(max_length=50)),
                ('ACCTNUM', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('ACCT_NAME', models.CharField(max_length=100)),
                ('ARREARSDAYS', models.IntegerField()),
                ('LCYBALANCE', models.DecimalField(decimal_places=2, max_digits=20)),
                ('TERM', models.CharField(max_length=50)),
                ('DIS_AMT', models.DecimalField(decimal_places=2, max_digits=20)),
                ('DIS_SHDL_DATE', models.DateField()),
                ('PRINCIPLE_BALANCE', models.DecimalField(decimal_places=2, max_digits=20)),
                ('DATE_ARREARS_START', models.DateField()),
                ('AMOUNT_CLAIMED', models.DecimalField(decimal_places=2, max_digits=20)),
                ('LOAN_CYCLE', models.CharField(default=1, max_length=50)),
                ('MODE_OF_ENGAGEMENT', models.CharField(default='DIRECT', max_length=50)),
                ('CLAIM_STATUS', models.CharField(default='ACTIVE', max_length=50)),
                ('AGE_CATEGORY', models.CharField(default='Below 20 years', max_length=100)),
                ('AGE', models.IntegerField()),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Client_Form_Info',
            fields=[
                ('ACCTNUM', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('GENDER', models.CharField(max_length=50)),
                ('LOAN_APP_DATE', models.DateField(blank=True)),
                ('ADDRESS', models.CharField(blank=True, max_length=255)),
                ('LOAN_PURPOSE', models.CharField(blank=True, max_length=255)),
                ('BUSINESS', models.CharField(blank=True, max_length=255)),
                ('GROUP', models.CharField(blank=True, max_length=100)),
                ('REASON_FOR_DEFAULT', models.CharField(blank=True, max_length=255)),
                ('SECTOR', models.CharField(max_length=50)),
                ('CONTACT', models.CharField(max_length=50)),
                ('COMPLETE', models.CharField(default='N', max_length=50)),
            ],
        ),
    ]
