# Generated by Django 5.0.3 on 2024-03-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_account',
            old_name='DOB',
            new_name='MAT_DATE',
        ),
        migrations.RemoveField(
            model_name='client_account',
            name='CLAIM_STATUS',
        ),
        migrations.RemoveField(
            model_name='client_form_info',
            name='BUSINESS',
        ),
        migrations.RemoveField(
            model_name='client_form_info',
            name='GENDER',
        ),
        migrations.AddField(
            model_name='client_account',
            name='BUSINESS_FINANCED',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client_account',
            name='CIF_ID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client_account',
            name='CUST_DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='client_account',
            name='FLOW_AMT',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='client_account',
            name='GENDER',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client_account',
            name='INDUSTRY_SECTOR',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client_account',
            name='NATIONAL_ID_REG_NUMBER',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client_account',
            name='LOAN_CYCLE',
            field=models.CharField(max_length=50),
        ),
    ]
