# Generated by Django 5.0.3 on 2024-03-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_dob_client_account_mat_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_account',
            name='BUSINESS_FINANCED',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
