# Generated by Django 5.0.3 on 2024-03-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_account_business_financed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_form_info',
            name='SECTOR',
        ),
    ]
