# Generated by Django 5.0.3 on 2024-03-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_client_form_info_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_form_info',
            name='COMPLETE',
        ),
        migrations.AlterField(
            model_name='client_account',
            name='BUSINESS_FINANCED',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client_account',
            name='INDUSTRY_SECTOR',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
