# Generated by Django 5.0.3 on 2024-04-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_client_form_info_complete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel_Report',
            fields=[
                ('ACCTNUM', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('ACCT_NAME', models.CharField(max_length=100)),
                ('LCYBALANCE', models.DecimalField(decimal_places=2, max_digits=20)),
                ('DIS_AMT', models.DecimalField(decimal_places=2, max_digits=20)),
                ('DIS_SHDL_DATE', models.DateField()),
                ('AMOUNT_CLAIMED', models.DecimalField(decimal_places=2, max_digits=20)),
                ('DATE_ARREARS_START', models.DateField()),
                ('GENDER', models.CharField(max_length=50, null=True)),
                ('AGE', models.IntegerField()),
                ('INDUSTRY_SECTOR', models.CharField(blank=True, max_length=50, null=True)),
                ('MODE_OF_ENGAGEMENT', models.CharField(default='DIRECT', max_length=50)),
                ('LOAN_CYCLE', models.CharField(max_length=50)),
                ('REASON_FOR_DEFAULT', models.CharField(blank=True, max_length=255)),
                ('CONTACT', models.CharField(max_length=50)),
            ],
        ),
    ]
