# Generated by Django 5.0.3 on 2024-04-05 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_excel_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excel_report',
            old_name='DATE_ARREARS_START',
            new_name='DATE_OF_DEFAULT',
        ),
        migrations.RenameField(
            model_name='excel_report',
            old_name='DIS_SHDL_DATE',
            new_name='DATE_OF_DISBURSEMENT',
        ),
        migrations.RenameField(
            model_name='excel_report',
            old_name='DIS_AMT',
            new_name='DISBURSED_AMOUNT',
        ),
        migrations.RenameField(
            model_name='excel_report',
            old_name='LCYBALANCE',
            new_name='LOAN_BALANCE',
        ),
        migrations.RenameField(
            model_name='excel_report',
            old_name='INDUSTRY_SECTOR',
            new_name='SECTOR_OF_VALUE_CHAI',
        ),
    ]
