# Generated by Django 5.0.3 on 2024-04-08 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_sector_of_value_chai_excel_report_sector_of_value_chain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excel_report',
            name='AGE',
        ),
        migrations.RemoveField(
            model_name='excel_report',
            name='GENDER',
        ),
        migrations.AlterField(
            model_name='client_account',
            name='LOAN_CYCLE',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='client_form_info',
            name='ACCTNUM',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.client_account'),
        ),
        migrations.AlterField(
            model_name='client_form_info',
            name='LOAN_APP_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excel_report',
            name='ACCTNUM',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.client_account'),
        ),
    ]
