# Generated by Django 5.0.3 on 2024-04-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_excel_report_age_remove_excel_report_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel_report',
            name='AGE',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excel_report',
            name='GENDER',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
