# Generated by Django 5.0.3 on 2024-04-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_excel_report_age_excel_report_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_account',
            name='LOAN_CYCLE',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client_form_info',
            name='ACCTNUM',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='client_form_info',
            name='LOAN_APP_DATE',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='excel_report',
            name='ACCTNUM',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
