# Generated by Django 5.0.3 on 2024-04-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_client_account_loan_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_form_info',
            name='CONTACT',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
